<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="Book1_20186" align=center x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=512 style='border-collapse:
 collapse;table-layout:fixed;width:384pt'>
 <col width=64 span=8 style='width:48pt'>
 <tr height=30 style='mso-height-source:userset;height:22.5pt'>
  <td rowspan=2 height=61 class=xl6920186 width=64 style='border-bottom:2.0pt double black;
  height:45.75pt;width:48pt'><span lang=EN-US style='mso-bidi-font-size:10pt'>Tahun
  Akade-mik</span></td>
  <td rowspan=2 class=xl7020186 width=64 style='border-bottom:2.0pt double black;
  width:48pt'><span lang=EN-US style='mso-bidi-font-family:Arial'>Daya Tampung</span></td>
  <td colspan=2 class=xl7420186 width=128 style='border-right:1.0pt solid black;
  border-left:none;width:96pt'><span lang=EN-US style='mso-bidi-font-family:
  Arial'>Jumlah Calon Mahasiswa<span style='mso-spacerun:yes'>  </span></span></td>
  <td colspan=2 class=xl7420186 width=128 style='border-right:1.0pt solid black;
  border-left:none;width:96pt'><span lang=EN-US style='mso-bidi-font-family:
  Arial'>Jumlah Mahasiswa Baru<span style='mso-spacerun:yes'> </span></span></td>
  <td colspan=2 class=xl7420186 width=128 style='border-right:1.0pt solid black;
  border-left:none;width:96pt'><span lang=EN-US style='mso-bidi-font-family:
  Arial'>Jumlah Total Mahasiswa</span></td>
 </tr>
 <tr height=31 style='height:23.25pt'>
  <td height=31 class=xl7220186 width=64 style='height:23.25pt;border-left:
  none;width:48pt'><span lang=EN-US style='mso-bidi-font-family:Arial'>Ikut
  Seleksi</span></td>
  <td class=xl7320186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>Lulus Seleksi</span></td>
  <td class=xl7320186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>Non-Reguler</span></td>
  <td class=xl7320186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>Transfer<font class="font520186"><sup>(3)</sup></font></span></td>
  <td class=xl7320186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>Non-Reguler</span></td>
  <td class=xl7320186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>Transfer<font class="font520186"><sup>(3)</sup></font></span></td>
 </tr>
 <tr height=22 style='height:16.5pt;mso-yfti-irow:2;page-break-inside:avoid'>
  <td height=22 class=xl6320186 width=64 style='height:16.5pt;width:48pt'><span
  lang=EN-US style='mso-bidi-font-family:Arial'>-1</span></td>
  <td class=xl6420186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>-2</span></td>
  <td class=xl6420186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>-3</span></td>
  <td class=xl6420186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>-4</span></td>
  <td class=xl6420186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>-5</span></td>
  <td class=xl6420186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>-6</span></td>
  <td class=xl6520186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>-7</span></td>
  <td class=xl6520186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>-8</span></td>
 </tr>
 <tr height=21 style='height:15.75pt;mso-yfti-irow:3;page-break-inside:avoid'>
  <td height=21 class=xl6620186 width=64 style='height:15.75pt;width:48pt'><span
  lang=EN-US>TS-4</span></td>
  <td class=xl6720186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl6720186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl6720186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl6720186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl6820186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl6820186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl6820186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
 </tr>
 <tr height=21 style='height:15.75pt;mso-yfti-irow:4;page-break-inside:avoid'>
  <td height=21 class=xl6620186 width=64 style='height:15.75pt;width:48pt'><span
  lang=EN-US>TS-3</span></td>
  <td class=xl6720186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl6720186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl6720186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl6720186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl6820186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl6820186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl6820186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
 </tr>
 <tr height=21 style='height:15.75pt;mso-yfti-irow:5;page-break-inside:avoid'>
  <td height=21 class=xl6620186 width=64 style='height:15.75pt;width:48pt'><span
  lang=EN-US>TS-2</span></td>
  <td class=xl6720186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl6720186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl6720186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl6720186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl6820186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl6820186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl6820186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
 </tr>
 <tr height=21 style='height:15.75pt;mso-yfti-irow:6;page-break-inside:avoid'>
  <td height=21 class=xl6620186 width=64 style='height:15.75pt;width:48pt'><span
  lang=EN-US>TS-1</span></td>
  <td class=xl6720186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl6720186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl6720186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl6720186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl6820186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl6820186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl6820186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
 </tr>
 <tr height=21 style='height:15.75pt;mso-yfti-irow:7;mso-yfti-lastrow:yes;
  page-break-inside:avoid'>
  <td height=21 class=xl6620186 width=64 style='height:15.75pt;width:48pt'><span
  lang=EN-US>TS</span></td>
  <td class=xl6720186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl6720186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl6720186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl6720186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl6820186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl6820186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl6820186 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
