<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div align=center>

<table border=0 cellpadding=0 cellspacing=0 width=1024 style='border-collapse:
 collapse;table-layout:fixed;width:768pt'>
 <col width=64 span=16 style='width:48pt'>
 <tr height=20 style='height:15.0pt'>
  <td rowspan=3 height=87 class=xl744007 width=64 style='border-bottom:2.0pt double black;
  height:65.25pt;width:48pt'><span lang=EN-US style='mso-bidi-font-size:10pt'>Tahun
  Akademik</span></td>
  <td rowspan=3 class=xl754007 width=64 style='border-bottom:2.0pt double black;
  width:48pt'><span lang=EN-US style='mso-bidi-font-family:Arial'>Daya Tampung</span></td>
  <td colspan=2 rowspan=2 class=xl764007 width=128 style='border-right:1.0pt solid black;
  border-bottom:1.0pt solid black;width:96pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>Jumlah Calon Mahasiswa Reguler<span
  style='mso-spacerun:yes'>  </span></span></td>
  <td colspan=2 rowspan=2 class=xl764007 width=128 style='border-right:1.0pt solid black;
  border-bottom:1.0pt solid black;width:96pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>Jumlah Mahasiswa Baru</span></td>
  <td colspan=2 rowspan=2 class=xl764007 width=128 style='border-right:1.0pt solid black;
  border-bottom:1.0pt solid black;width:96pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>Jumlah Total Mahasiswa</span></td>
  <td colspan=2 rowspan=2 class=xl764007 width=128 style='border-right:1.0pt solid black;
  border-bottom:1.0pt solid black;width:96pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>Jumlah Lulusan<span
  style='mso-spacerun:yes'> </span></span></td>
  <td colspan=3 class=xl764007 width=192 style='border-right:1.0pt solid black;
  border-left:none;width:144pt'><span lang=EN-US style='mso-bidi-font-family:
  Arial'>IPK<span style='mso-spacerun:yes'> </span></span></td>
  <td colspan=3 class=xl764007 width=192 style='border-right:1.0pt solid black;
  border-left:none;width:144pt'><span lang=EN-US style='mso-bidi-font-family:
  Arial'>Persentase Lulusan Reguler</span></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td colspan=3 height=21 class=xl814007 width=192 style='border-right:1.0pt solid black;
  height:15.75pt;border-left:none;width:144pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>Lulusan Reguler</span></td>
  <td colspan=3 class=xl814007 width=192 style='border-right:1.0pt solid black;
  border-left:none;width:144pt'><span lang=EN-US style='mso-bidi-font-family:
  Arial'><span style='mso-spacerun:yes'> </span>dengan IPK :</span></td>
 </tr>
 <tr height=46 style='height:34.5pt'>
  <td height=46 class=xl854007 width=64 style='height:34.5pt;border-left:none;
  width:48pt'><span lang=EN-US style='mso-bidi-font-family:Arial'>Ikut Seleksi</span></td>
  <td class=xl864007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>Lulus Seleksi</span></td>
  <td class=xl864007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>Regular bukan Transfer</span></td>
  <td class=xl864007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>Transfer<font class="font54007"><sup>(3)</sup></font></span></td>
  <td class=xl864007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>Reguler bukan Transfer</span></td>
  <td class=xl864007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>Transfer<font class="font54007"><sup>(3)</sup></font></span></td>
  <td class=xl864007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>Reguler bukan Transfer</span></td>
  <td class=xl864007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>Transfer<font class="font54007"><sup>(3)</sup></font></span></td>
  <td class=xl864007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>Min</span></td>
  <td class=xl864007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>Rat</span></td>
  <td class=xl864007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>Mak</span></td>
  <td class=xl864007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>&lt; 2,75</span></td>
  <td class=xl864007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>2,75-3,50</span></td>
  <td class=xl864007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>&gt; 3,50</span></td>
 </tr>
 <tr height=22 style='height:16.5pt;mso-yfti-irow:2;page-break-inside:avoid'>
  <td height=22 class=xl634007 width=64 style='height:16.5pt;width:48pt'><span
  lang=EN-US style='mso-bidi-font-family:Arial'>-1</span></td>
  <td class=xl644007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>-2</span></td>
  <td class=xl644007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>-3</span></td>
  <td class=xl644007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>-4</span></td>
  <td class=xl644007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>-5</span></td>
  <td class=xl644007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>-6</span></td>
  <td class=xl654007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>-7</span></td>
  <td class=xl654007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>-8</span></td>
  <td class=xl654007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>-9</span></td>
  <td class=xl654007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>-10</span></td>
  <td class=xl644007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>-11</span></td>
  <td class=xl644007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>-12</span></td>
  <td class=xl644007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>-13</span></td>
  <td class=xl644007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>-14</span></td>
  <td class=xl644007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>-15</span></td>
  <td class=xl644007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial'>-16</span></td>
 </tr>
 <tr height=21 style='height:15.75pt;mso-yfti-irow:3;page-break-inside:avoid'>
  <td height=21 class=xl664007 width=64 style='height:15.75pt;width:48pt'><span
  lang=EN-US>TS-4</span></td>
  <td class=xl674007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl674007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl674007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl674007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
 </tr>
 <tr height=21 style='height:15.75pt;mso-yfti-irow:4;page-break-inside:avoid'>
  <td height=21 class=xl664007 width=64 style='height:15.75pt;width:48pt'><span
  lang=EN-US>TS-3</span></td>
  <td class=xl694007 width=64 style='width:48pt'>&nbsp;</td>
  <td class=xl674007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl674007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl674007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
 </tr>
 <tr height=21 style='height:15.75pt;mso-yfti-irow:5;page-break-inside:avoid'>
  <td height=21 class=xl664007 width=64 style='height:15.75pt;width:48pt'><span
  lang=EN-US>TS-2</span></td>
  <td class=xl674007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl674007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl674007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl674007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
 </tr>
 <tr height=21 style='height:15.75pt;mso-yfti-irow:6;page-break-inside:avoid'>
  <td height=21 class=xl664007 width=64 style='height:15.75pt;width:48pt'><span
  lang=EN-US>TS-1</span></td>
  <td class=xl674007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl674007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl674007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl674007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
 </tr>
 <tr height=21 style='height:15.75pt;mso-yfti-irow:7;page-break-inside:avoid'>
  <td height=21 class=xl704007 width=64 style='height:15.75pt;width:48pt'><span
  lang=EN-US>TS</span></td>
  <td class=xl714007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl714007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl714007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl714007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl724007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl724007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl724007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl724007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl724007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl724007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl724007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl724007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl724007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl724007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl724007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
 </tr>
 <tr height=22 style='height:16.5pt;mso-yfti-irow:8;mso-yfti-lastrow:yes;
  page-break-inside:avoid'>
  <td height=22 class=xl664007 width=64 style='height:16.5pt;width:48pt'><span
  lang=EN-US>Jumlah</span></td>
  <td class=xl674007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl674007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl674007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl674007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl684007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl734007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl734007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl734007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl734007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl734007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl734007 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
