
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="Book1_17682" align=center x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=576 style='border-collapse:collapse;table-layout:fixed;width:432pt'>
	<col width=64 span=9 style='width:48pt'>
		<tr height=46 style='height:34.5pt'>
			<td rowspan=2 height=92 class=xl6817682 width=64 style='border-bottom:1.0pt solid black;
			height:69.0pt;width:48pt'>
				<span lang=EN-US style='mso-bidi-font-size:10pt'>
					Tahun Masuk
				</span>
			</td>
			<td colspan=7 class=xl7217682 width=448 style='border-right:1.0pt solid black;
			border-left:none;width:336pt'>
				<span lang=EN-US style='mso-bidi-font-size:10pt'>
					Jumlah Mahasiswa Reguler per Angkatan pada Tahun*
				</span>
			</td>
			<td class=xl7017682 width=64 style='width:48pt'>
				<span lang=EN-US style='mso-bidi-font-size:10pt'>Jumlah Lulusan s.d. TS</span>
			</td>
		</tr>
		<tr height=46 style='height:34.5pt'>
			<td height=46 class=xl6917682 width=64 style='height:34.5pt;width:48pt'><span
  lang=EN-US style='mso-bidi-font-size:10pt'>TS-6</span></td>
  <td class=xl6917682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-size:10pt'>TS-5</span></td>
  <td class=xl6917682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-size:10pt'>TS-4</span></td>
  <td class=xl6917682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-size:10pt'>TS-3</span></td>
  <td class=xl6917682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-size:10pt'>TS-2</span></td>
  <td class=xl6917682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-size:10pt'>TS-1</span></td>
  <td class=xl6917682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-size:10pt'>TS</span></td>
  <td class=xl7117682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-size:10pt'>(dari Mahasiswa Reguler)</span></td>
 </tr>
 <tr height=21 style='height:15.75pt;mso-yfti-irow:2;page-break-inside:avoid'>
  <td height=21 class=xl6517682 width=64 style='height:15.75pt;width:48pt'><span
  lang=EN-US style='mso-bidi-font-size:10pt'>-1</span></td>
  <td class=xl6617682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-size:10pt'>-1</span></td>
  <td class=xl6617682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-size:10pt'>-2</span></td>
  <td class=xl6617682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-size:10pt'>-3</span></td>
  <td class=xl6617682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-size:10pt'>-4</span></td>
  <td class=xl6617682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-size:10pt'>-5</span></td>
  <td class=xl6617682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-size:10pt'>-6</span></td>
  <td class=xl6617682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-size:10pt'>-7</span></td>
  <td class=xl6617682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-size:10pt'>-8</span></td>
 </tr>
 <tr height=21 style='height:15.75pt;mso-yfti-irow:3;page-break-inside:avoid'>
  <td height=21 class=xl6717682 width=64 style='height:15.75pt;width:48pt'><span
  lang=EN-US>TS-6</span></td>
  <td class=xl7417682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>(a)=</span></td>
  <td class=xl7417682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl7417682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl7417682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl7417682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl7417682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl7417682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>(b)=</span></td>
  <td class=xl7417682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>(c)=</span></td>
 </tr>
 <tr height=21 style='height:15.75pt;mso-yfti-irow:4;page-break-inside:avoid'>
  <td height=21 class=xl6717682 width=64 style='height:15.75pt;width:48pt'><span
  lang=EN-US>TS-5</span></td>
  <td class=xl8417682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl7417682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl7617682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl7617682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl7617682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl7617682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl7617682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl7417682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
 </tr>
 <tr height=21 style='height:15.75pt;mso-yfti-irow:5;page-break-inside:avoid'>
  <td height=21 class=xl6717682 width=64 style='height:15.75pt;width:48pt'><span
  lang=EN-US>TS-4</span></td>
  <td class=xl8517682 width=64 style='width:48pt'></td>
  <td class=xl8417682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl7417682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl7617682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl7617682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl7617682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl7717682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl7417682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
 </tr>
 <tr height=21 style='height:15.75pt;mso-yfti-irow:6;page-break-inside:avoid'>
  <td height=21 class=xl6717682 width=64 style='height:15.75pt;width:48pt'><span
  lang=EN-US>TS-3</span></td>
  <td class=xl8517682 width=64 style='width:48pt'></td>
  <td class=xl8517682 width=64 style='width:48pt'></td>
  <td class=xl8417682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl7417682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>(d) =</span></td>
  <td class=xl7617682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl7617682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl7817682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>(e) =</span></td>
  <td class=xl7417682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>(f) =</span></td>
 </tr>
 <tr height=21 style='height:15.75pt;mso-yfti-irow:7;page-break-inside:avoid'>
  <td height=21 class=xl6717682 width=64 style='height:15.75pt;width:48pt'><span
  lang=EN-US>TS-2</span></td>
  <td class=xl8517682 width=64 style='width:48pt'></td>
  <td class=xl8517682 width=64 style='width:48pt'></td>
  <td class=xl8517682 width=64 style='width:48pt'></td>
  <td class=xl8417682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl7617682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl7517682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl7617682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl8417682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
 </tr>
 <tr height=21 style='height:15.75pt;mso-yfti-irow:8;page-break-inside:avoid'>
  <td height=21 class=xl7917682 width=64 style='height:15.75pt;width:48pt'><span
  lang=EN-US>TS-1</span></td>
  <td class=xl8517682 width=64 style='width:48pt'></td>
  <td class=xl8517682 width=64 style='width:48pt'></td>
  <td class=xl8517682 width=64 style='width:48pt'></td>
  <td class=xl8517682 width=64 style='width:48pt'></td>
  <td class=xl8417682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl8017682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl7517682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl8417682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
 </tr>
 <tr height=21 style='height:15.75pt;mso-yfti-irow:9;mso-yfti-lastrow:yes;
  page-break-inside:avoid'>
  <td height=21 class=xl8117682 width=64 style='height:15.75pt;width:48pt'><span
  lang=EN-US>TS</span></td>
  <td class=xl8617682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl8617682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl8617682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl8617682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl8617682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl8717682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl8017682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
  <td class=xl8717682 width=64 style='width:48pt'><span lang=EN-US
  style='mso-bidi-font-family:Arial;mso-bidi-font-size:10pt'>&nbsp;</span></td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
